language: go

dist: focal

go:
- 1.21.x
- 1.22.x
- 1.23.x


notifications:
  email: true

before_install:
  - pyenv global 3.8

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.61.0

script:
  - make travis-ci

before_deploy:
  - nvm install 18
  - node --version
  - npm --version
  - npm install
  - pip install --user bump-my-version

deploy:
  - provider: script
    script: npm run semantic-release
    skip_cleanup: true
    on:
      go: '1.21.x'
      branch: master