/* Code generated by cmd/cgo; DO NOT EDIT. */



#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) uintptr_t CreateSessionC(char* endpoint, int port, char* instanceID, char* cryptoUnitID, char* username, char* keyfile, char* passphrase, char* iamToken);
extern __declspec(dllexport) int CloseSessionC(uintptr_t sessionID);
extern __declspec(dllexport) int SetTokenGetterC(uintptr_t sessionID, char* tokenCStr);
extern __declspec(dllexport) int GetAuthStateC(uintptr_t sessionID, int* authState);
extern __declspec(dllexport) int ListUsersC(uintptr_t sessionID, char** result);
extern __declspec(dllexport) int AddUserC(uintptr_t sessionID, char* username, char* userType, char* credential, char* credHash, char* attributes, char* headers, char** result);
extern __declspec(dllexport) int DeleteUserC(uintptr_t sessionID, char* username);
extern __declspec(dllexport) int GenerateRSAKeyC(char* instanceID, char* keySpec, uint32_t keySizeBits, char* owner, char* passphrase, char** result);
extern __declspec(dllexport) int GenerateECDSAKeyC(char* instanceID, char* keySpec, char* curve, char* owner, char* passphrase, char** result);
extern __declspec(dllexport) int ListMBKKeysC(uintptr_t sessionID, char** result);
extern __declspec(dllexport) int GenerateMBKC(uintptr_t sessionID, char* keyspec, char* keytype, int keylen, uint8_t n, uint8_t k, char* keyname, char* headers, char** result);
extern __declspec(dllexport) int ImportMBKC(uintptr_t sessionID, char* keyspec, int slotNo, char* headers, char** result);
extern __declspec(dllexport) int ChangeUserPasswordC(uintptr_t sessionID, char* username, char* oldPassword, char* newPassword);
extern __declspec(dllexport) int GetCryptoUnitIDC(uintptr_t sessionID, char** result);
extern __declspec(dllexport) void FreeStringC(char* str);
extern __declspec(dllexport) int GetLastErrorC(uintptr_t sessionID, char** result);
extern __declspec(dllexport) int InitalizeCryptoUnitC(char** result);

#ifdef __cplusplus
}
#endif
